add missing #include; fixes undefined reference to AG_Redraw().
git-svn-id: https://dev.csoft.net/agar/trunk@8815 86a84d31-9702-0410-8f1e-a60cab7bd424